include "/etc/thehive/secret.conf"

db.janusgraph {
  storage {
    backend = cql
    hostname = ["thehive-cassandra"]
    username = cassandra
    password = cassandra
    cql {
      cluster-name = thp
      keyspace = thehive
    }
  }
  index.search {
    backend = elasticsearch
    hostname = ["thehive-elasticsearch"]
    index-name = thehive
    elasticsearch {
      http.auth.type = basic
      http.auth.basic.username = elastic
      http.auth.basic.password = ${?THEHIVE_ES_PASSWORD}
    }
  }
}

storage.provider = localfs
storage.localfs.location = /opt/thp/thehive/files
application.baseUrl = "http://localhost:9000"
play.http.secret.key = ${?THEHIVE_SECRET}
