"""baseline schema

Revision ID: c0518a8363a8
Revises: 
Create Date: 2026-07-11 03:32:51.285482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c0518a8363a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'player', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_settings',
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_settings_id'), 'ai_settings', ['id'], unique=False)
    op.create_table('scenarios',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('iocs', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'generating', 'generated', 'validation_failed', 'ready', 'published', name='scenariostatus'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('attack_steps', sa.JSON(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('containment_actions',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_containment_actions_id'), 'containment_actions', ['id'], unique=False)
    op.create_table('indicators',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_table('lab_groups',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='labgroupstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_groups_id'), 'lab_groups', ['id'], unique=False)
    op.create_index(op.f('ix_lab_groups_scenario_id'), 'lab_groups', ['scenario_id'], unique=False)
    op.create_table('player_labs',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_labs_id'), 'player_labs', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('required_keywords', sa.JSON(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('related_event_ids', sa.JSON(), nullable=True),
    sa.Column('related_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('scenario_artifacts',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('related_event_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_artifacts_id'), 'scenario_artifacts', ['id'], unique=False)
    op.create_table('scenario_events',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_events_id'), 'scenario_events', ['id'], unique=False)
    op.create_table('scenario_traces',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('trace_type', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('parent_process', sa.String(), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('network_target', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_traces_id'), 'scenario_traces', ['id'], unique=False)
    op.create_table('scenario_traffic',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flow_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_traffic_id'), 'scenario_traffic', ['id'], unique=False)
    op.create_table('lab_activity_log',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_activity_log_group_id'), 'lab_activity_log', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_activity_log_id'), 'lab_activity_log', ['id'], unique=False)
    op.create_table('lab_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_lab_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'lead_analyst', 'analyst', 'observer', name='labgrouprole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_lab_id'], ['player_labs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_lab_group_member')
    )
    op.create_index(op.f('ix_lab_group_members_group_id'), 'lab_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_group_members_id'), 'lab_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_lab_group_members_user_id'), 'lab_group_members', ['user_id'], unique=False)
    op.create_table('lab_invitations',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'lead_analyst', 'analyst', 'observer', name='labgrouprole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='invitationstatus'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_invitations_group_id'), 'lab_invitations', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_invitations_id'), 'lab_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_lab_invitations_invited_user_id'), 'lab_invitations', ['invited_user_id'], unique=False)
    op.create_table('lab_messages',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_messages_group_id'), 'lab_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_messages_id'), 'lab_messages', ['id'], unique=False)
    op.create_table('lab_personal_progress',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.JSON(), nullable=True),
    sa.Column('evidence_viewed', sa.JSON(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('questions_solved', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_lab_personal_progress')
    )
    op.create_index(op.f('ix_lab_personal_progress_group_id'), 'lab_personal_progress', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_personal_progress_id'), 'lab_personal_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lab_personal_progress_user_id'), 'lab_personal_progress', ['user_id'], unique=False)
    op.create_table('lab_presence',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('online', 'idle', 'away', 'offline', name='presencestatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_lab_presence')
    )
    op.create_index(op.f('ix_lab_presence_group_id'), 'lab_presence', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_presence_id'), 'lab_presence', ['id'], unique=False)
    op.create_index(op.f('ix_lab_presence_user_id'), 'lab_presence', ['user_id'], unique=False)
    op.create_table('lab_tasks',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mitre_id', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tasks_group_id'), 'lab_tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_lab_tasks_id'), 'lab_tasks', ['id'], unique=False)
    op.create_table('lab_workspaces',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('required_tools', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('provisioning_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['player_labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id')
    )
    op.create_index(op.f('ix_lab_workspaces_id'), 'lab_workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_lab_workspaces_workspace_id'), 'lab_workspaces', ['workspace_id'], unique=True)
    op.create_table('player_answers',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('attached_evidence', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['player_labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_answers_id'), 'player_answers', ['id'], unique=False)
    op.create_table('player_scores',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('question_score', sa.Float(), nullable=True),
    sa.Column('containment_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_possible', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['player_labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_scores_id'), 'player_scores', ['id'], unique=False)
    op.create_table('shared_evidence',
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('ioc', 'event', 'artifact', 'custom', name='evidencetype'), nullable=False),
    sa.Column('evidence_ref_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('related_ioc', sa.String(), nullable=True),
    sa.Column('related_mitre_technique', sa.String(), nullable=True),
    sa.Column('visibility', sa.Enum('lab', name='evidencevisibility'), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['player_labs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_evidence_id'), 'shared_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_shared_evidence_investigation_id'), 'shared_evidence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_shared_evidence_lab_id'), 'shared_evidence', ['lab_id'], unique=False)
    op.create_index(op.f('ix_shared_evidence_owner_id'), 'shared_evidence', ['owner_id'], unique=False)
    op.create_table('shared_notes',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['lab_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_notes_group_id'), 'shared_notes', ['group_id'], unique=False)
    op.create_index(op.f('ix_shared_notes_id'), 'shared_notes', ['id'], unique=False)
    op.create_table('shared_note_history',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['shared_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_note_history_id'), 'shared_note_history', ['id'], unique=False)
    op.create_index(op.f('ix_shared_note_history_note_id'), 'shared_note_history', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_note_history_note_id'), table_name='shared_note_history')
    op.drop_index(op.f('ix_shared_note_history_id'), table_name='shared_note_history')
    op.drop_table('shared_note_history')
    op.drop_index(op.f('ix_shared_notes_id'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_group_id'), table_name='shared_notes')
    op.drop_table('shared_notes')
    op.drop_index(op.f('ix_shared_evidence_owner_id'), table_name='shared_evidence')
    op.drop_index(op.f('ix_shared_evidence_lab_id'), table_name='shared_evidence')
    op.drop_index(op.f('ix_shared_evidence_investigation_id'), table_name='shared_evidence')
    op.drop_index(op.f('ix_shared_evidence_id'), table_name='shared_evidence')
    op.drop_table('shared_evidence')
    op.drop_index(op.f('ix_player_scores_id'), table_name='player_scores')
    op.drop_table('player_scores')
    op.drop_index(op.f('ix_player_answers_id'), table_name='player_answers')
    op.drop_table('player_answers')
    op.drop_index(op.f('ix_lab_workspaces_workspace_id'), table_name='lab_workspaces')
    op.drop_index(op.f('ix_lab_workspaces_id'), table_name='lab_workspaces')
    op.drop_table('lab_workspaces')
    op.drop_index(op.f('ix_lab_tasks_id'), table_name='lab_tasks')
    op.drop_index(op.f('ix_lab_tasks_group_id'), table_name='lab_tasks')
    op.drop_table('lab_tasks')
    op.drop_index(op.f('ix_lab_presence_user_id'), table_name='lab_presence')
    op.drop_index(op.f('ix_lab_presence_id'), table_name='lab_presence')
    op.drop_index(op.f('ix_lab_presence_group_id'), table_name='lab_presence')
    op.drop_table('lab_presence')
    op.drop_index(op.f('ix_lab_personal_progress_user_id'), table_name='lab_personal_progress')
    op.drop_index(op.f('ix_lab_personal_progress_id'), table_name='lab_personal_progress')
    op.drop_index(op.f('ix_lab_personal_progress_group_id'), table_name='lab_personal_progress')
    op.drop_table('lab_personal_progress')
    op.drop_index(op.f('ix_lab_messages_id'), table_name='lab_messages')
    op.drop_index(op.f('ix_lab_messages_group_id'), table_name='lab_messages')
    op.drop_table('lab_messages')
    op.drop_index(op.f('ix_lab_invitations_invited_user_id'), table_name='lab_invitations')
    op.drop_index(op.f('ix_lab_invitations_id'), table_name='lab_invitations')
    op.drop_index(op.f('ix_lab_invitations_group_id'), table_name='lab_invitations')
    op.drop_table('lab_invitations')
    op.drop_index(op.f('ix_lab_group_members_user_id'), table_name='lab_group_members')
    op.drop_index(op.f('ix_lab_group_members_id'), table_name='lab_group_members')
    op.drop_index(op.f('ix_lab_group_members_group_id'), table_name='lab_group_members')
    op.drop_table('lab_group_members')
    op.drop_index(op.f('ix_lab_activity_log_id'), table_name='lab_activity_log')
    op.drop_index(op.f('ix_lab_activity_log_group_id'), table_name='lab_activity_log')
    op.drop_table('lab_activity_log')
    op.drop_index(op.f('ix_scenario_traffic_id'), table_name='scenario_traffic')
    op.drop_table('scenario_traffic')
    op.drop_index(op.f('ix_scenario_traces_id'), table_name='scenario_traces')
    op.drop_table('scenario_traces')
    op.drop_index(op.f('ix_scenario_events_id'), table_name='scenario_events')
    op.drop_table('scenario_events')
    op.drop_index(op.f('ix_scenario_artifacts_id'), table_name='scenario_artifacts')
    op.drop_table('scenario_artifacts')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_player_labs_id'), table_name='player_labs')
    op.drop_table('player_labs')
    op.drop_index(op.f('ix_lab_groups_scenario_id'), table_name='lab_groups')
    op.drop_index(op.f('ix_lab_groups_id'), table_name='lab_groups')
    op.drop_table('lab_groups')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_containment_actions_id'), table_name='containment_actions')
    op.drop_table('containment_actions')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_ai_settings_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate doesn't drop the Postgres ENUM *types* themselves when it
    # drops the tables that use them (SQLAlchemy only auto-creates them,
    # checkfirst, on table creation) - without this, re-running `upgrade`
    # after a `downgrade` fails with "type already exists".
    for enum_name in (
        "userrole", "scenariostatus", "difficultylevel",
        "labgroupstatus", "labgrouprole", "invitationstatus",
        "taskstatus", "presencestatus", "evidencetype", "evidencevisibility",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
